package com.platform.api.models

enum class ERole
{
    ROLE_STUDENT, ROLE_MODERATOR, ROLE_ADMIN,
    ROLE_FIRST_GRADE, ROLE_SECOND_GRADE, ROLE_THIRD_GRADE,
    ROLE_BOOK_CLUB, ROLE_SOCCER_CLUB, ROLE_BASKETBALL_CLUB,
    ROLE_GAME_CLUB, ROLE_FOOD_CLUB, ROLE_STUDENT_PRESIDENT,
    ROLE_STUDENT_VICE_PRESIDENT, ROLE_GRADUATE
}